POST http://localhost:3333/user
// metadado que o front-end precisa enviar para dizer qual tipo de arquivo que ta sendo enviado
Content-Type: application/json

{
    "nome": "samuel araujo de oliveira",
    "email": "araujosamuel@gmail.com",
    "senha": "senha123456"
}

###
// os '####' separam as requisições
GET http://localhost:3333/user
###
// os '####' separam as requisições
GET http://localhost:3333/user?search=samuel
###
// os '####' separam as requisições
GET http://localhost:3333/user?search=samuel@gmail.com

###
PUT http://localhost:3333/user/2
// metadado que o front-end precisa enviar para dizer qual tipo de arquivo que ta sendo enviado
Content-Type: application/json

{
    "nome": "matheus araujo",
    "email": "matheus@gmail.com",
    "senha": "senha123"
}

###

DELETE http://localhost:3333/user/delete/2
// metadado que o front-end precisa enviar para dizer qual tipo de arquivo que ta sendo enviado

