POST http://localhost:3333/user
// metadado que o front-end precisa enviar para dizer qual tipo de arquivo que ta sendo enviado
Content-Type: application/json

{
    "nome": "samuel 01",
    "email": "mumuca1999@gmail.com",
    "senha": "senha123"
}

###
// os '####' separam as requisições
GET http://localhost:3333/user?search=samuel

###
// os '####' separam as requisições
GET http://localhost:3333/user?search=mumuca1999@gmail.com
###
// os '####' separam as requisições
GET http://localhost:3333/user

###
PUT http://localhost:3333/user/30250d27-6489-462f-9fb7-3da2ed3f44ef
// metadado que o front-end precisa enviar para dizer qual tipo de arquivo que ta sendo enviado
Content-Type: application/json

{
    "nome": "samuel 00",
    "email": "mumuca1999@gmail.com",
    "senha": "senha123"
}

###

DELETE http://localhost:3333/user/delete/30250d27-6489-462f-9fb7-3da2ed3f44ef
// metadado que o front-end precisa enviar para dizer qual tipo de arquivo que ta sendo enviado

